[package]
name = "riddle-macros"
version = "0.1.0"
authors = ["vickles <vicklesort@gmail.com>"]
edition = "2018"

[lib]
proc-macros = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
